script: 'git submodule update --init; bundle exec rake test:travis'

env:
  - 'RESTGRAPH=rest-graph'
  - 'RESTGRAPH=rails2'
  - 'RESTGRAPH=rails3'

rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - rbx-18mode
  - rbx-19mode
  - jruby-18mode
  - jruby-19mode
