before_install: 'git submodule update --init'
script: 'ruby -r bundler/setup -S rake test:travis'

env:
  - 'RESTGRAPH=rest-graph'
  - 'RESTGRAPH=rails3'

rvm:
  - 1.9
  - 2.0
  - 2.1
  - rbx
  - jruby
